name: Continuous Integration

on:
  push:

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        compiler: [ clang, gcc ]
        type: [ Debug, Release ]
        exclude:
          - os: macos-latest
            compiler: gcc
          - os: windows-latest
            compiler: gcc
        include:
          - os: macos-latest
            compiler: gcc-14
            type: Debug
          - os: macos-latest
            compiler: gcc-14
            type: Release
    steps:
      - name: Checkpout repository
        uses: actions/checkout@v5
      - name: Initialize Environment
        uses: ROOT-Sim/ci-actions/init@v1.5.2
      - name: Build & Test
        uses: ROOT-Sim/ci-actions/cmake@v1.5.2
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.compiler }}
          build-type: ${{ matrix.type }}
          run-test: true
